In [34]:
import csv
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib notebook
pd.options.display.max_rows = 35

alldata=csv.reader(open('D:/new/高等学校招生人数（万人）分省年度数据 (1).csv','r'))
#alldata = pd.read_table('C:/Users/Administrator/Desktop/Python课件与书籍/地区生产总值季度数据.csv')#,sep='::',header=None,names=pnames)
alldata
alldata_panda=pd.DataFrame(alldata)
alldata_panda
database1=pd.DataFrame(alldata_panda.drop([0,1,2,35]))
database=pd.DataFrame(database1.drop([0,1],1))
database.index=database1[0][:32]
database.columns=database1.T[3][2:11]
database
database=pd.DataFrame(database.drop(['地区']))
database=database.astype('float')#强制类型转换
databaseT=database.T
databaseT.columns=['北京','天津','河北','山西','内蒙古','辽宁','吉林','黑龙江','上海','江苏', '浙江', '安徽', '福建', '江西', '山东', '河南', '湖北', '湖南', '广东',
                 '广西', '海南', '重庆', '四川', '贵州', '云南', '西藏', '陕西', '甘肃','青海', '宁夏', '新疆']
databaseT.sort_values(by='2017年',axis=1)

,西藏,青海,宁夏,海南,新疆,内蒙古,甘肃,上海,天津,北京,...,江西,安徽,湖南,河北,湖北,四川,江苏,山东,广东,河南
3,,,,,,,,,,,,,,,,,,,,,
2017年,0.97,1.96,3.47,5.22,10.37,12.21,13.15,13.56,13.87,15.05,...,28.85,30.72,35.79,36.51,39.41,43.30,45.66,54.85,55.84,56.94
2016年,1.01,1.91,3.24,5.32,9.22,12.19,12.58,13.75,13.90,15.12,...,29.60,30.74,34.94,35.79,39.07,41.47,45.27,55.52,53.98,55.01
2015年,0.99,1.80,3.22,5.24,8.72,11.90,12.43,13.68,13.86,15.35,...,28.68,32.65,33.63,32.91,38.54,41.33,44.86,54.08,55.06,51.47
2014年,0.88,1.55,3.28,5.45,8.28,11.56,12.93,13.80,13.92,15.69,...,28.32,31.03,32.66,31.82,39.31,38.62,44.49,53.36,53.54,47.42
2013年,0.93,1.48,3.07,4.93,8.10,11.24,12.23,13.72,13.86,15.98,...,24.74,29.66,31.37,32.59,39.89,35.78,43.95,49.16,51.69,46.67
2012年,1.00,1.46,3.08,4.96,7.58,10.56,13.02,13.68,13.72,15.86,...,23.77,28.62,31.10,32.14,40.21,36.45,43.50,46.67,50.19,45.53
2011年,0.94,1.40,2.82,4.64,7.40,11.41,12.35,13.78,13.12,15.69,...,24.60,30.80,30.61,34.90,40.95,34.36,43.61,48.08,46.87,44.89
2010年,0.92,1.30,2.50,4.76,7.36,11.25,11.41,14.46,12.86,15.51,...,24.85,28.76,30.27,33.91,38.76,33.21,44.86,47.52,43.73,45.71
2009年,0.90,1.26,2.24,4.64,6.76,10.91,10.95,14.35,11.88,15.98,...,23.89,26.79,31.44,32.92,37.33,29.97,42.98,46.91,43.59,42.99

In [50]:
from pyecharts.charts import Map
from example.commons import Faker
from pyecharts import options as opts

def map_visualmap() -> Map:
    c = (
        Map()
        .add("高校招生人数", [list(z) for z in zip(attr,values)], "china")
        .set_global_opts(
            title_opts=opts.TitleOpts(title="地区高等学校招生人数2017年（万人）"),
            #visualmap_opts=opts.VisualMapOpts(min_=0.97,max_=56.94, is_piecewise=True),
            visualmap_opts=opts.VisualMapOpts(min_=0,max_=0.075)#, is_piecewise=True),
        )
    )
    return c
attr=list(databaseT.columns)
values=databaseT.values.tolist()[0]
values=list(np.array(values)/sum(values))
print(attr)
print(values)
#list(z) for z in zip(attr,values)
z = list(zip(attr,values))
print(z)
#map1=Map()
#map1=Map("各省GDP总值", '单位：亿元',width=1200,height=600)
#map1.add("", attr, values, type="effectScatter", is_random=True, visual_range=[0, 100], 
 #       maptype='china', geo_emphasis_color='#F5D0A9',visual_text_color="#6E6E6E",
 #        is_visualmap=True, is_map_symbol_show=False)
map1=map_visualmap()
map1.render('C:\\Users\\Administrator\\render_招生.html')

['北京', '天津', '河北', '山西', '内蒙古', '辽宁', '吉林', '黑龙江', '上海', '江苏', '浙江', '安徽', '福建', '江西', '山东', '河南', '湖北', '湖南', '广东', '广西', '海南', '重庆', '四川', '贵州', '云南', '西藏', '陕西', '甘肃', '青海', '宁夏', '新疆']
[0.019763624425476026, 0.018214051214707806, 0.04794484569927772, 0.026697307944845684, 0.016034143138542345, 0.03280367695338147, 0.022481943532501634, 0.02563361785948784, 0.017806959947472088, 0.059960604070912644, 0.033565331582403136, 0.04034143138542349, 0.026263952724885083, 0.03788575180564673, 0.07202889034799734, 0.07477347340774783, 0.051753118844386055, 0.04699934340118186, 0.07332895600787916, 0.03504924491135915, 0.006854891661195007, 0.027511490479317124, 0.0568614576493762, 0.026224556795797754, 0.02653972422849638, 0.0012738017071569265, 0.037386736703873914, 0.017268548916611944, 0.002573867367038738, 0.004556795797767562, 0.013617859487852916]
[('北京', 0.019763624425476026), ('天津', 0.018214051214707806), ('河北', 0.04794484569927772), ('山西', 0.026697307944845684), ('内蒙古', 0.016034143138542345), ('辽宁', 0.03280367695338147), ('吉林', 0.022481943532501634), ('黑龙江', 0.02563361785948784), ('上海', 0.017806959947472088), ('江苏', 0.059960604070912644), ('浙江', 0.033565331582403136), ('安徽', 0.04034143138542349), ('福建', 0.026263952724885083), ('江西', 0.03788575180564673), ('山东', 0.07202889034799734), ('河南', 0.07477347340774783), ('湖北', 0.051753118844386055), ('湖南', 0.04699934340118186), ('广东', 0.07332895600787916), ('广西', 0.03504924491135915), ('海南', 0.006854891661195007), ('重庆', 0.027511490479317124), ('四川', 0.0568614576493762), ('贵州', 0.026224556795797754), ('云南', 0.02653972422849638), ('西藏', 0.0012738017071569265), ('陕西', 0.037386736703873914), ('甘肃', 0.017268548916611944), ('青海', 0.002573867367038738), ('宁夏', 0.004556795797767562), ('新疆', 0.013617859487852916)]

'C:\\Users\\Administrator\\render_招生.html'